Make TickGen compatible with current builtin
numaproj/numaflow pull request #2162
Opened 2024-10-16 16:33 UTC by BulkBeing

Resolves  #2158

2024-10-17 07:25 UTC, yhl25 commented on rust/numaflow-core/src/config.rs
> +                    config.value = generator_source.value;
if content is set, should we set this to None?

2024-10-17 07:25 UTC, yhl25 commented on rust/numaflow-core/src/source/generator.rs
> +            }
```suggestion
            let padding: Vec<u8> = (msg_size_bytes > 8)
                .then(|| {
                    let size = (msg_size_bytes - 8);
                    let mut bytes = vec![0; size as usize];
                    rand::thread_rng().fill(&mut bytes[..]);
                    bytes
                })
                .unwrap_or_default();
```

2024-10-17 07:25 UTC, yhl25 commented on rust/numaflow-core/src/source/generator.rs
> +                    }
can we extract this out? so that it can be used inside poll pending also?

2024-10-17 07:25 UTC, yhl25 commented on rust/numaflow-core/src/source/generator.rs
> +        keys: (Vec<String>, usize),
should we reset the usize after every tick?

2024-10-17 09:42 UTC, yhl25 approved these changes
LGTM!

2024-10-17 15:00 UTC, vigith requested changes
we need to pass self

2024-10-17 22:21 UTC, vigith commented
try something like this? the key point is, `this` and `self` cannot be having overlapping lifetimes.

```rust
use std::{
    pin::Pin,
    task::{Context, Poll},
    time::Duration,
};

use futures::{Stream, StreamExt};
use pin_project::pin_project;

#[pin_project]
struct Generator {
    size: usize,
    #[pin]
    interval: tokio::time::Interval,
}

impl Generator {
    fn new(size: usize, duration: Duration) -> Self {
        Self {
            size,
            interval: tokio::time::interval(duration),
        }
    }

    fn increment_size(&mut self) -> usize {
        self.size += 1;
        self.size
    }
}

impl Stream for Generator {
    type Item = usize;

    fn poll_next(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        let mut this = self.as_mut().project();
        match this.interval.poll_tick(cx) {
            Poll::Ready(_) => {
                let size = self.increment_size();
                Poll::Ready(Some(size))
            }
            Poll::Pending => Poll::Pending,
        }
    }
}

#[tokio::main]
async fn main() {
    let mut gen = Generator::new(0, Duration::from_millis(100));
    for _ in 0..10 {
        let l = &gen.next().await.unwrap();
        println!("{}", l);
    }
}
```

2024-10-18 16:02 UTC, vigith approved these changes

2024-10-18 16:35 UTC, merged