chore: add best practices section in docs
numaproj/numaflow pull request #2184
Opened 2024-10-24 06:02 UTC by kohlisid

2024-10-24 06:13 UTC, whynowy commented on mkdocs.yml
> +      - Best Practices: operations/best-practices.md
`Best Practices` as a folder, and different pages for different topics?

2024-11-01 18:09 UTC, KeranYang approved these changes

2024-11-04 18:25 UTC, kohlisid commented
@whynowy Are you good to merge?

2024-11-04 18:32 UTC, whynowy commented on docs/operations/best-practices/udf.md
> +be 0 during the silent period. Refer [Autoscaling](https://numaflow.numaproj.io/user-guide/reference/autoscaling/) for more information
```suggestion
be 0 during the silent period. Refer [Autoscaling](../../user-guide/reference/autoscaling.md) for more information  
```

2024-11-05 22:12 UTC, whynowy approved these changes

2024-11-05 22:23 UTC, vigith requested changes
let's figure out why rate == 0

2024-11-17 19:21 UTC, vigith commented
> let's figure out why rate == 0

@kohlisid are you looking into this?

2024-11-18 01:09 UTC, kohlisid commented
@vigith Yes!

2024-11-18 01:12 UTC, vigith commented
can you please link the issue if you have any?

2024-11-18 01:12 UTC, vigith commented
i want to close this one out.

2024-11-18 01:26 UTC, kohlisid commented
We can use this issue
https://github.com/numaproj/numaflow/issues/1407

2025-04-29 17:50 UTC, vigith commented
closing this since we have auto lookback now. please reopen if this is still required.

2025-04-29 17:50 UTC, closed without merging