chore: enable map stream udf e2e test for python and java sdk
numaproj/numaflow pull request #779
Opened 2023-06-07 05:31 UTC by xdevxy

Closes https://github.com/numaproj/numaflow/issues/778

2023-06-07 15:06 UTC, KeranYang commented
E2E failed？

2023-06-07 15:07 UTC, KeranYang requested changes
E2E failed

2023-06-07 23:04 UTC, xdevxy commented
> E2E failed

This is very weird. It is passing on my local env but continuously with different image build. I guess this is something to do with the image being used. But not sure what happended.

2023-06-08 00:29 UTC, KeranYang approved these changes

2023-06-08 00:32 UTC, merged